### ISSUE TITLE
monogame 3.8

### ISSUE THREAD

**Issue by ghost** [Ragath/TiledLib.Net#11]
Hi

Is the code up to date for monogame 3.8 and which nuget package to use?

Thx

**Comment by Ragath** [comment]
I haven't tested it, but it should still work. You'd ideally use the Tiled.Pipeline package in your content pipeline project and write a custom processor that takes the Tiled types and turns them into something more suitable for your particular game.

You could also use the Tiled package in the game and parse the Tiled format at runtime. It has no dependencies on MonoGame itself.

**Comment by ghost** [comment]
Can you put some complete examples online with a Tiled map that's been read and shown the information?
As a beginner it's very hard to find out how to use it, and there are no docs too.

For example how to find out what kind of tile image is used in each tile of the map?
I need this in my game.

**Comment by Ragath** [comment]
fixed in v4.0.0
