### ISSUE TITLE
Add `TileAnimations`  to `ITileset`

### ISSUE THREAD

**Issue by danielscherzer** [Ragath/TiledLib.Net#7]
Hi,
`Tilset` includes a `public Dictionary<int, Frame[]> TileAnimations { get; }`. When I inspect the values for my animations they seem all to be correct. But `TileAnimations` is not exported into `ITileset`. Still I can't use it because `Tilset` is a private member of `ExternalTilset`. So I would need to do some nasty reflection to get to. Is this the intended way or am I missing something?
Thanks for your time, Daniel!

**Comment by Ragath** [comment]
For now the workaround would be to cast, but I do intend to expose it in the interface. I remember there being an issue with them in combination with external tilesets, but hopefully that's been resolved.

**Comment by danielscherzer** [comment]
Ok! Thanks! For all others interested one workaround for now is with reflection:
```
T GetPrivateProperty<T>(object obj, string name)
{
	BindingFlags flags = BindingFlags.Instance | BindingFlags.NonPublic;
	Type type = obj.GetType();
	PropertyInfo field = type.GetProperty(name, flags);
	return (T)field.GetValue(obj, null);
}
var tileset = GetPrivateProperty<TiledLib.Tileset>(map.Tilesets[0], "Tileset");
tileset.TileAnimations...
```

**Comment by Ragath** [comment]
seems to work ok, so resolving this with the v3.2.0 release
